Feature/location dropdown
xu-jenny/spacious-mvp pull request #10
Opened 2024-08-27 22:51 UTC by KoiOne

<img width="504" alt="image" src="https://github.com/user-attachments/assets/e308b96b-5c95-464b-a8d6-a3f7966189f2">
<img width="920" alt="IMG_8482" src="https://github.com/user-attachments/assets/a217e08b-c44f-4d4a-8701-208c79f30266">
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/19e9c517-ec74-44e0-9252-3130c699f51b">
<img width="799" alt="image" src="https://github.com/user-attachments/assets/38420f05-34de-4d78-baca-9ae523685b2d">

2024-08-27 23:12 UTC, xu-jenny requested changes

2024-08-27 23:12 UTC, xu-jenny commented on components/index/SearchResult/USGSWaterdatasetCard.tsx
> +          <FlowTooltip content={``}>
If there's no content let's remove the Tooltip

2024-08-27 23:12 UTC, xu-jenny commented on components/index/LocationInfo.tsx
> +  const parseLocation = (display_name: string | null) => {
I think this parseLocation logic is too weak. The string is not always guaranteed to be formatted this way

2024-08-28 03:30 UTC, xu-jenny commented on components/index/DatasetPane/USGSWaterDatasetPane.tsx
> +        parameterCode: "00045", //dataset.matchingParamCode,
Why is this hardcoded

2024-08-28 15:01 UTC, KoiOne commented
<img width="616" alt="IMG_6063" src="https://github.com/user-attachments/assets/a57fc538-00ce-4871-b87f-e653ea64747a">
<img width="492" alt="IMG_0607" src="https://github.com/user-attachments/assets/0f895199-1a33-4b4c-af94-502ee14aefbb">
<img width="935" alt="image" src="https://github.com/user-attachments/assets/cbfd2699-78f5-47be-933f-8e1201037a0f">

2024-08-28 15:06 UTC, xu-jenny approved these changes

2024-08-28 15:06 UTC, merged